#!/bin/bash -ex
export PATH=/home/users/dwatsonparris/miniconda3/envs/cis_env/bin:$PATH
#cdo -mulc,-1.0 -chname,ahfl,hfls -selvar,ahfl -mergetime /gws/nopw/j04/eo_shared_data_vol2/scratch/dwatsonparris/gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Raw/abrupt_zero_bc_coupled_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Data/hfls_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_coupled_200001-210001.nc
#cdo -mulc,-1.0 -chname,ahfs,hfss -selvar,ahfs -mergetime /gws/nopw/j04/eo_shared_data_vol2/scratch/dwatsonparris/gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Raw/abrupt_zero_bc_coupled_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Data/hfss_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_coupled_200001-210001.nc
cdo -mulc,1.0 -chname,temp2,tas -selvar,temp2 -mergetime /gws/nopw/j04/eo_shared_data_vol2/scratch/dwatsonparris/gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Raw/abrupt_zero_bc_coupled_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Data/tas_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_coupled_200001-210001.nc
cdo -mulc,1.0 -chname,evap,evspsbl -selvar,evap -mergetime /gws/nopw/j04/eo_shared_data_vol2/scratch/dwatsonparris/gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Raw/abrupt_zero_bc_coupled_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_coupled/Data/evspsbl_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_coupled_200001-210001.nc
cdo -mulc,-1.0 -chname,ahfl,hfls -selvar,ahfl -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Raw/abrupt_zero_bc_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Data/hfls_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_fsst_200001-210001.nc
cdo -mulc,-1.0 -chname,ahfs,hfss -selvar,ahfs -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Raw/abrupt_zero_bc_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Data/hfss_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_fsst_200001-210001.nc
cdo -mulc,1.0 -chname,temp2,tas -selvar,temp2 -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Raw/abrupt_zero_bc_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Data/tas_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_fsst_200001-210001.nc
cdo -mulc,1.0 -chname,evap,evspsbl -selvar,evap -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Raw/abrupt_zero_bc_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_bc_fsst/Data/evspsbl_Amon_ECHAM6.3-HAM2.2_abrupt_zero_bc_fsst_200001-210001.nc
cdo -mulc,-1.0 -chname,ahfl,hfls -selvar,ahfl -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Raw/abrupt_zero_so4_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Data/hfls_Amon_ECHAM6.3-HAM2.2_abrupt_zero_sul_fsst_200001-210001.nc
cdo -mulc,-1.0 -chname,ahfs,hfss -selvar,ahfs -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Raw/abrupt_zero_so4_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Data/hfss_Amon_ECHAM6.3-HAM2.2_abrupt_zero_sul_fsst_200001-210001.nc
cdo -mulc,1.0 -chname,temp2,tas -selvar,temp2 -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Raw/abrupt_zero_so4_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Data/tas_Amon_ECHAM6.3-HAM2.2_abrupt_zero_sul_fsst_200001-210001.nc
cdo -mulc,1.0 -chname,evap,evspsbl -selvar,evap -mergetime /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Raw/abrupt_zero_so4_fsst_*_echam.nc /gws/nopw/j04/impala/users/dwatsonparris/abrupt_zero_so4_fsst/Data/evspsbl_Amon_ECHAM6.3-HAM2.2_abrupt_zero_sul_fsst_200001-210001.nc
